services:
  db-dev:
    image: postgres
    volumes:
      - ../data-dev/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: sinpp-dev
    command: sh -c "poetry install --no-root && tsc && . .venv/bin/activate && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=[""]
      - CSRF_TRUSTED_ORIGINS=[""]
      - CSRF_COOKIE_SECURE=True
      - SESSION_COOKIE_SECURE=True
      - DEBUG=True
      - SECRET_KEY=
      - STATIC=
      - STATIC_ROOT=
      - DB_USER=postgres
      - DB_TABLE=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db-dev
      - DB_PORT=5432
    depends_on:
      - db-dev
    volumes:
      # Don't forget about static
      - "../sinpp:/sinpp"
