# Generated by Django 4.2.2 on 2023-06-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('SHORT_TITLE', models.CharField(max_length=25)),
                ('START_DATE_TIME', models.DateTimeField()),
                ('END_DATE_TIME', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NICKNAME', models.CharField(max_length=25)),
                ('PRONOUNS', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('HOUR_BASED', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_DATE_TIME', models.DateTimeField()),
                ('END_DATE_TIME', models.DateTimeField()),
                ('ROLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.role')),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.person')),
            ],
        ),
        migrations.CreateModel(
            name='Speedrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GAME', models.CharField(max_length=25)),
                ('CATEGORY', models.CharField(max_length=25)),
                ('START_TIME', models.DateTimeField()),
                ('ESTIMATE', models.DurationField()),
                ('END_TIME', models.DateTimeField()),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
                ('VOLUNTEERS_COMMENTATING', models.ManyToManyField(related_name='SPEEDRUNS_COMMENTATED', to='schedule.person')),
                ('VOLUNTEERS_RUNNING', models.ManyToManyField(related_name='SPEEDRUNS_RAN', to='schedule.person')),
                ('VOLUNTEER_SHIFTS', models.ManyToManyField(to='schedule.shift')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='ROLES',
            field=models.ManyToManyField(to='schedule.role'),
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_DATE_TIME', models.DateTimeField()),
                ('END_DATE_TIME', models.DateTimeField()),
                ('PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.person')),
            ],
        ),
    ]
