# Generated by Django 4.2.2 on 2023-06-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityblock',
            name='EVENT',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='EVENT',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='VISIBILITY',
            field=models.CharField(choices=[('RL', 'Role Staff'), ('ES', 'Event Staff'), ('PU', 'Public')], default='RL', max_length=25),
        ),
        migrations.AddField(
            model_name='shift',
            name='EVENT',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='PRONOUNS',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='speedrun',
            name='CATEGORY',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
