# Generated by Django 4.2.2 on 2023-06-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_availabilityblock_event_role_event_role_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedrun',
            name='VOLUNTEERS_COMMENTATING',
        ),
        migrations.RemoveField(
            model_name='speedrun',
            name='VOLUNTEERS_RUNNING',
        ),
        migrations.AddField(
            model_name='speedrun',
            name='VOLUNTEERS_ENGAGED',
            field=models.ManyToManyField(related_name='SPEEDRUNS_ENGAGED_IN', to='schedule.person'),
        ),
    ]
