# Generated by Django 4.2.2 on 2023-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_speedrun_volunteers_commentating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ROLES',
            field=models.ManyToManyField(blank=True, to='schedule.role'),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='VOLUNTEER',
        ),
        migrations.AlterField(
            model_name='speedrun',
            name='VOLUNTEER_SHIFTS',
            field=models.ManyToManyField(blank=True, to='schedule.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='VOLUNTEER',
            field=models.ManyToManyField(to='schedule.person'),
        ),
    ]
