# Generated by Django 4.2.2 on 2023-08-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_intermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrun',
            name='CATEGORY',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='speedrun',
            name='GAME',
            field=models.CharField(max_length=100),
        ),
    ]
