# Generated by Django 4.2.2 on 2023-08-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_speedrun_category_alter_speedrun_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='TIME_SAFETY_MARGIN',
        ),
        migrations.AddField(
            model_name='role',
            name='TIME_SAFETY_MARGIN',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
