# Generated by Django 4.2.2 on 2023-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_event_time_safety_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='HOUR_BASED',
        ),
        migrations.AddField(
            model_name='role',
            name='TYPE',
            field=models.CharField(choices=[('HB', 'Hour-based'), ('SB', 'Speedrun-based'), ('IB', 'Intermission-based')], default='HB', max_length=25),
        ),
    ]
