# Generated by Django 4.2.2 on 2023-08-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_role_hour_based_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
                ('SPEEDRUNS', models.ManyToManyField(to='schedule.speedrun')),
            ],
        ),
        migrations.AddField(
            model_name='speedrun',
            name='ROOM',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room'),
        ),
    ]
