# Generated by Django 4.2.2 on 2023-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_room_speedrun_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='VOLUNTEERS',
            field=models.ManyToManyField(blank=True, to='schedule.person'),
        ),
    ]
