# Generated by Django 4.2.2 on 2023-08-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_role_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='VOLUNTEERS',
        ),
    ]
