# Generated by Django 4.2.2 on 2023-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_intermission_room_shift_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='VISIBILITY',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PR', max_length=25),
        ),
    ]
