# Generated by Django 4.2.2 on 2023-09-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schedule', '0015_alter_role_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='STAFF',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='staff_of', to='auth.group'),
            preserve_default=False,
        ),
    ]
