# Generated by Django 4.2.2 on 2023-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_event_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='SPEEDRUNS',
            field=models.ManyToManyField(blank=True, to='schedule.speedrun'),
        ),
    ]
