# Generated by Django 4.2.2 on 2023-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_room_speedruns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SHORT_TITLE',
            field=models.SlugField(max_length=25),
        ),
    ]
