# Generated by Django 4.2.2 on 2023-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_event_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='SLUG',
            field=models.SlugField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='SHORT_TITLE',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
