# Generated by Django 4.2.2 on 2023-09-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='SPEEDRUNS',
        ),
    ]
