# Generated by Django 4.2.2 on 2023-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_remove_room_speedruns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrun',
            name='VOLUNTEERS_ENGAGED',
            field=models.ManyToManyField(blank=True, related_name='SPEEDRUNS_ENGAGED_IN', to='schedule.person'),
        ),
    ]
