# Generated by Django 4.2.2 on 2023-11-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_rename_short_title_event_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermission',
            name='VOLUNTEER_SHIFTS',
        ),
        migrations.RemoveField(
            model_name='speedrun',
            name='VOLUNTEER_SHIFTS',
        ),
    ]
