# Generated by Django 4.2.2 on 2023-11-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_remove_intermission_volunteer_shifts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='SLUG',
            field=models.SlugField(max_length=25),
        ),
    ]
