# Generated by Django 4.2.2 on 2023-11-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_alter_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='VOLUNTEER',
            new_name='VOLUNTEERS',
        ),
    ]
