# Generated by Django 4.2.2 on 2023-11-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_rename_volunteer_shift_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='TYPE',
        ),
        migrations.RemoveField(
            model_name='role',
            name='VISIBILITY',
        ),
    ]
